def iniciar_juego():
    score=0
    print("##############################################")
    print("#                         O             O    #")
    print("#                      ---||        ----||   #")
    print("#                         ||            ||   #")
    print("#                                O           #")
    print("#  O                         ----||          #")
    print("# ||---                          ||          #")
    print("# ||                                         #")
    print("##############################################")
    print("comenzando demo")
    import random
    comando=random.randint(0,1)
    print("con el comando (FUEGO) disparar automaticamente")
    disparar=libreria.validar_comando(input("IMPRIMA COMANDO"))
    if disparar=="FUEGO":
        print("#################################################")
        print("#   o                       O           O     #")
        print("#  ||----  ------------O  --||        ----||    #")
        print("#  ||                       ||            ||    #")
        print("#                           O                   #")
        print("#                         --||                  #")
        print("#                           ||                  #")
        print("#                                               #")
        print("#################################################")
        fuego=random.randint(0,1)
        if fuego==comando:
            print("#################################################")
            print("#   o                         O           O     #")
            print("#  ||----  ------------O  --||        ----||    #")
            print("#  ||                       ||            ||    #")
            print("#                           O                   #")
            print("#                         --||                  #")
            print("#                           ||                  #")
            print("#                                               #")
            print("#################################################")
            print("OBJETIVO ELIMINADO")
            score+=250
            disparar = libreria.validar_comando(input("IMPRIMA COMANDO"))
            if disparar == "FUEGO":
                print("#################################################")
                print("#   o                                   O       #")
                print("#  ||----  --------- o              ----||      #")
                print("#  ||                                   ||      #")
                print("#                           O                   #")
                print("#                         --||                  #")
                print("#                           ||                  #")
                print("#                                               #")
                print("#################################################")
                fuego = random.randint(0, 1)
                if fuego == comando:
                    print("#################################################")
                    print("#   o                                       O   #")
                    print("#  ||----  ------------O              ----||    #")
                    print("#  ||                                     ||    #")
                    print("#                           O                   #")
                    print("#                         --||                  #")
                    print("#                           ||                  #")
                    print("#                                               #")
                    print("#################################################")
                    print("OBJETIVO ELIMINADO")
                    score += 250
                    disparar = libreria.validar_comando(input("IMPRIMA COMANDO"))
                    if disparar == "FUEGO":
                        print("#################################################")
                        print("#                                               #")
                        print("#                                               #")
                        print("#                                               #")
                        print("#    o                         O                #")
                        print("#   ||--------------------O ---||               #")
                        print("#   ||                         ||               #")
                        print("#                                               #")
                        print("#################################################")
                        fuego = random.randint(0, 1)
                        if fuego == comando:
                            print("#################################################")
                            print("#                                               #")
                            print("#                                               #")
                            print("#                                               #")
                            print("#    o                           O                #")
                            print("#   ||--------------------O ---||               #")
                            print("#   ||                         ||               #")
                            print("#                                               #")
                            print("#################################################")
                            print("OBJETIVO ELIMINADO")
                            score += 250
                            print("juego terminado")
                            rpta=input("DESEA GUARDAR SU SCORE? SI(1) O NO(0): ")
                            nombre=libreria.validar_contacto(input("Inrese su nombre"))
                            if rpta=="1":
                                arcivo=open("score.txt","a")
                                arcivo.write("\n"+"nombre: "+nombre+"\n"+"Su score final es: "+str(score))
                                print("se ha guardado correctamente")
                                arcivo.close()
                            else:
                                print("ok no se guardara el score")
                        else:
                            print("##################################################")
                            print("#                                                #")
                            print("#                                                #")
                            print("#                                                #")
                            print("#                                                #")
                            print("#   o                                            #")
                            print("#  ||----                                        #")
                            print("#  ||                                            #")
                            print("##################################################")
                            print("El objetivo a escapado ")
                            score += 0
                            print("juego terminado")
                            rpta = input("DESEA GUARDAR SU SCORE? SI(1) O NO(0): ")
                            nombre = libreria.validar_contacto(input("Inrese su nombre"))
                            if rpta == "1":
                                arcivo = open("score.txt", "a")
                                arcivo.write("\n" + "nombre: " + nombre + "\n" + "Su score final es: " + str(score))
                                print("se ha guardado correctamente")
                                arcivo.close()
                            else:
                                print("ok no se guardara ningun")
                    else:
                        fuego = random.randint(0, 1)
                        if fuego == comando:
                            print("#################################################")
                            print("#                                               #")
                            print("#                                               #")
                            print("#                                               #")
                            print("#    o                           O                #")
                            print("#   ||--------------------O ---||               #")
                            print("#   ||                         ||               #")
                            print("#                                               #")
                            print("#################################################")
                            print("OBJETIVO ELIMINADO")
                            score += 250
                            print("juego terminado")
                            rpta = input("DESEA GUARDAR SU SCORE? SI(1) O NO(0): ")
                            nombre = libreria.validar_contacto(input("Inrese su nombre"))
                            if rpta == "1":
                                arcivo = open("score.txt", "a")
                                arcivo.write("\n" + "nombre: " + nombre + "\n" + "Su score final es: " + str(score))
                                print("se ha guardado correctamente")
                                arcivo.close()
                            else:
                                print("ok no se guardara el score")
                        else:
                            print("##################################################")
                            print("#                                                #")
                            print("#                                                #")
                            print("#                                                #")
                            print("#                                                #")
                            print("#   o                                            #")
                            print("#  ||----                                        #")
                            print("#  ||                                            #")
                            print("##################################################")
                            print("El objetivo a escapado ")
                            score += 0
                            print("juego terminado")
                            rpta = input("DESEA GUARDAR SU SCORE? SI(1) O NO(0): ")
                            nombre = libreria.validar_contacto(input("Inrese su nombre"))
                            if rpta == "1":
                                arcivo = open("score.txt", "a")
                                arcivo.write("\n" + "nombre: " + nombre + "\n" + "Su score final es: " + str(score))
                                print("se ha guardado correctamente")
                                arcivo.close()
                            else:
                                print("ok no se guardara ningun dato")


            else:
                    print("#################################################")
                    print("#   o                                           #")
                    print("#  ||----                                       #")
                    print("#  ||                                           #")
                    print("#                           O                   #")
                    print("#                         --||                  #")
                    print("#                           ||                  #")
                    print("#                                               #")
                    print("#################################################")
                    print("El objetivo a escapado ")
                    score += 0
                    disparar = libreria.validar_comando(input("IMPRIMA COMANDO"))
                    fuego = random.randint(0, 1)
                    if fuego == comando:
                        print("#################################################")
                        print("#   o                                       O   #")
                        print("#  ||----  ------------O              ----||    #")
                        print("#  ||                                     ||    #")
                        print("#                           O                   #")
                        print("#                         --||                  #")
                        print("#                           ||                  #")
                        print("#                                               #")
                        print("#################################################")
                        print("OBJETIVO ELIMINADO")
                        score += 250
                        disparar = libreria.validar_comando(input("IMPRIMA COMANDO"))
                        if disparar == "FUEGO":
                            print("#################################################")
                            print("#                                               #")
                            print("#                                               #")
                            print("#                                               #")
                            print("#    o                         O                #")
                            print("#   ||--------------------O ---||               #")
                            print("#   ||                         ||               #")
                            print("#                                               #")
                            print("#################################################")
                            fuego = random.randint(0, 1)
                            if fuego == comando:
                                print("#################################################")
                                print("#                                               #")
                                print("#                                               #")
                                print("#                                               #")
                                print("#    o                           O                #")
                                print("#   ||--------------------O ---||               #")
                                print("#   ||                         ||               #")
                                print("#                                               #")
                                print("#################################################")
                                print("OBJETIVO ELIMINADO")
                                score += 250
                                print("juego terminado")
                                rpta = input("DESEA GUARDAR SU SCORE? SI(1) O NO(0): ")
                                nombre = libreria.validar_contacto(input("Inrese su nombre"))
                                if rpta == "1":
                                    arcivo = open("score.txt", "a")
                                    arcivo.write("\n" + "nombre: " + nombre + "\n" + "Su score final es: " + str(score))
                                    print("se ha guardado correctamente")
                                    arcivo.close()
                                else:
                                    print("ok no se guardara el score")
                            else:
                                print("##################################################")
                                print("#                                                #")
                                print("#                                                #")
                                print("#                                                #")
                                print("#                                                #")
                                print("#   o                                            #")
                                print("#  ||----                                        #")
                                print("#  ||                                            #")
                                print("##################################################")
                                print("El objetivo a escapado ")
                                score += 0
                                print("juego terminado")
                                rpta = input("DESEA GUARDAR SU SCORE? SI(1) O NO(0): ")
                                nombre = libreria.validar_contacto(input("Inrese su nombre"))
                                if rpta == "1":
                                    arcivo = open("score.txt", "a")
                                    arcivo.write("\n" + "nombre: " + nombre + "\n" + "Su score final es: " + str(score))
                                    print("se ha guardado correctamente")
                                    arcivo.close()
                                else:
                                    print("ok no se guardara ningun")
                        else:
                            fuego = random.randint(0, 1)
                            if fuego == comando:
                                print("#################################################")
                                print("#                                               #")
                                print("#                                               #")
                                print("#                                               #")
                                print("#    o                           O                #")
                                print("#   ||--------------------O ---||               #")
                                print("#   ||                         ||               #")
                                print("#                                               #")
                                print("#################################################")
                                print("OBJETIVO ELIMINADO")
                                score += 250
                                print("juego terminado")
                                rpta = input("DESEA GUARDAR SU SCORE? SI(1) O NO(0): ")
                                nombre = libreria.validar_contacto(input("Inrese su nombre"))
                                if rpta == "1":
                                    arcivo = open("score.txt", "a")
                                    arcivo.write("\n" + "nombre: " + nombre + "\n" + "Su score final es: " + str(score))
                                    print("se ha guardado correctamente")
                                    arcivo.close()
                                else:
                                    print("ok no se guardara el score")
                            else:
                                print("##################################################")
                                print("#                                                #")
                                print("#                                                #")
                                print("#                                                #")
                                print("#                                                #")
                                print("#   o                                            #")
                                print("#  ||----                                        #")
                                print("#  ||                                            #")
                                print("##################################################")
                                print("El objetivo a escapado ")
                                score += 0
                                print("juego terminado")
                                rpta = input("DESEA GUARDAR SU SCORE? SI(1) O NO(0): ")
                                nombre = libreria.validar_contacto(input("Inrese su nombre"))
                                if rpta == "1":
                                    arcivo = open("score.txt", "a")
                                    arcivo.write("\n" + "nombre: " + nombre + "\n" + "Su score final es: " + str(score))
                                    print("se ha guardado correctamente")
                                    arcivo.close()
                                else:
                                    print("ok no se guardara ningun dato")

            fuego = random.randint(0, 1)
            if fuego == comando:
                print("#################################################")
                print("#                                               #")
                print("#                                               #")
                print("#                                               #")
                print("#    o                           O                #")
                print("#   ||--------------------O ---||               #")
                print("#   ||                         ||               #")
                print("#                                               #")
                print("#################################################")
                print("OBJETIVO ELIMINADO")
                score += 250
                print("juego terminado")
                rpta = input("DESEA GUARDAR SU SCORE? SI(1) O NO(0): ")
                nombre = libreria.validar_contacto(input("Inrese su nombre"))
                if rpta == "1":
                    arcivo = open("score.txt", "a")
                    arcivo.write("\n" + "nombre: " + nombre + "\n" + "Su score final es: " + str(score))
                    print("se ha guardado correctamente")
                    arcivo.close()
                else:
                    print("ok no se guardara el score")
            else:
                print("##################################################")
                print("#                                                #")
                print("#                                                #")
                print("#                                                #")
                print("#                                                #")
                print("#   o                                            #")
                print("#  ||----                                        #")
                print("#  ||                                            #")
                print("##################################################")
                print("El objetivo a escapado ")
                score += 0
                print("juego terminado")
                rpta = input("DESEA GUARDAR SU SCORE? SI(1) O NO(0): ")
                nombre = libreria.validar_contacto(input("Inrese su nombre"))
                if rpta == "1":
                    arcivo = open("score.txt", "a")
                    arcivo.write("\n" + "nombre: " + nombre + "\n" + "Su score final es: " + str(score))
                    print("se ha guardado correctamente")
                    arcivo.close()
                else:
                    print("ok no se guardara ningun dato")


        else:
            print("#################################################")
            print("#   o                                     O     #")
            print("#  ||----                             ----||    #")
            print("#  ||                                     ||    #")
            print("#                           O                   #")
            print("#                         --||                  #")
            print("#                           ||                  #")
            print("#                                               #")
            print("#################################################")
            print("El objetivo a escapado ")
            score+=0
            disparar = libreria.validar_comando(input("IMPRIMA COMANDO"))
            if disparar == "FUEGO":
                print("#################################################")
                print("#   o                                   O       #")
                print("#  ||----  --------- o              ----||      #")
                print("#  ||                                   ||      #")
                print("#                           O                   #")
                print("#                         --||                  #")
                print("#                           ||                  #")
                print("#                                               #")
                print("#################################################")
                fuego = random.randint(0, 1)
                if fuego == comando:
                    print("#################################################")
                    print("#   o                                       O   #")
                    print("#  ||----  ------------O              ----||    #")
                    print("#  ||                                     ||    #")
                    print("#                           O                   #")
                    print("#                         --||                  #")
                    print("#                           ||                  #")
                    print("#                                               #")
                    print("#################################################")
                    print("OBJETIVO ELIMINADO")
                    score += 250
                    disparar = libreria.validar_comando(input("IMPRIMA COMANDO"))#

                else:
                    print("#################################################")
                    print("#   o                                           #")
                    print("#  ||----                                       #")
                    print("#  ||                                           #")
                    print("#                           O                   #")
                    print("#                         --||                  #")
                    print("#                           ||                  #")
                    print("#                                               #")
                    print("#################################################")
                    print("El objetivo a escapado ")
                    score += 0
                    disparar = libreria.validar_comando(input("IMPRIMA COMANDO"))
                    fuego = random.randint(0, 1)
                    if fuego == comando:
                        print("#################################################")
                        print("#                                               #")
                        print("#                                               #")
                        print("#                                               #")
                        print("#    o                           O              #")
                        print("#   ||--------------------O ---||               #")
                        print("#   ||                         ||               #")
                        print("#                                               #")
                        print("#################################################")
                        print("OBJETIVO ELIMINADO")
                        score += 250
                        print("juego terminado")
                        rpta = input("DESEA GUARDAR SU SCORE? SI(1) O NO(0): ")
                        nombre = libreria.validar_contacto(input("Inrese su nombre"))
                        if rpta == "1":
                            arcivo = open("score.txt", "a")
                            arcivo.write("\n" + "nombre: " + nombre + "\n" + "Su score final es: " + str(score))
                            print("se ha guardado correctamente")
                            arcivo.close()
                        else:
                            print("ok no se uardo ninun dato")
                    else:
                        print("##################################################")
                        print("#                                                #")
                        print("#                                                #")
                        print("#                                                #")
                        print("#                                                #")
                        print("#   o                                            #")
                        print("#  ||----                                        #")
                        print("#  ||                                            #")
                        print("##################################################")
                        print("El objetivo a escapado ")
                        score += 0
                        print("juego terminado")
                        rpta = input("DESEA GUARDAR SU SCORE? SI(1) O NO(0): ")
                        nombre = libreria.validar_contacto(input("Inrese su nombre"))
                        if rpta == "1":
                            arcivo = open("score.txt", "a")
                            arcivo.write("\n" + "nombre: " + nombre + "\n" + "Su score final es: " + str(score))
                            print("se ha guardado correctamente")
                            arcivo.close()
                        else:
                            print("ok no se guardara ningun dato")
            else:

                    print("#################################################")
                    print("#   o                                           #")
                    print("#  ||----                                       #")
                    print("#  ||                                           #")
                    print("#                           O                   #")
                    print("#                         --||                  #")
                    print("#                           ||                  #")
                    print("#                                               #")
                    print("#################################################")
                    print("El objetivo a escapado ")
                    score += 0
                    disparar = libreria.validar_comando(input("IMPRIMA COMANDO"))
                    fuego = random.randint(0, 1)
                    if fuego == comando:
                        print("#################################################")
                        print("#                                               #")
                        print("#                                               #")
                        print("#                                               #")
                        print("#    o                           O              #")
                        print("#   ||--------------------O ---||               #")
                        print("#   ||                         ||               #")
                        print("#                                               #")
                        print("#################################################")
                        print("OBJETIVO ELIMINADO")
                        score += 250
                        print("juego terminado")
                        rpta = input("DESEA GUARDAR SU SCORE? SI(1) O NO(0): ")
                        nombre = libreria.validar_contacto(input("Inrese su nombre"))
                        if rpta == "1":
                            arcivo = open("score.txt", "a")
                            arcivo.write("\n" + "nombre: " + nombre + "\n" + "Su score final es: " + str(score))
                            print("se ha guardado correctamente")
                            arcivo.close()
                        else:
                            print("ok no se uardo ninun dato")

                    else:
                        print("##################################################")
                        print("#                                                #")
                        print("#                                                #")
                        print("#                                                #")
                        print("#                                                #")
                        print("#   o                                            #")
                        print("#  ||----                                        #")
                        print("#  ||                                            #")
                        print("##################################################")
                        print("El objetivo a escapado ")
                        score +=0
                        print("juego terminado")
                        rpta = input("DESEA GUARDAR SU SCORE? SI(1) O NO(0): ")
                        nombre = libreria.validar_contacto(input("Inrese su nombre"))
                        if rpta == "1":
                            arcivo = open("score.txt", "a")
                            arcivo.write("\n" + "nombre: " + nombre + "\n" + "Su score final es: " + str(score))
                            print("se ha guardado correctamente")
                            arcivo.close()
                        else:
                            print("ok no se guardara ningun dato")
    else:

        disparar = libreria.validar_comando(input("IMPRIMA COMANDO"))
        if disparar == "FUEGO":
            print("#################################################")
            print("#   o                                   O       #")
            print("#  ||----  --------- o              ----||      #")
            print("#  ||                                   ||      #")
            print("#                           O                   #")
            print("#                         --||                  #")
            print("#                           ||                  #")
            print("#                                               #")
            print("#################################################")
            fuego = random.randint(0, 1)
            if fuego == comando:
                print("#################################################")
                print("#   o                                       O   #")
                print("#  ||----  ------------O              ----||    #")
                print("#  ||                                     ||    #")
                print("#                           O                   #")
                print("#                         --||                  #")
                print("#                           ||                  #")
                print("#                                               #")
                print("#################################################")
                print("OBJETIVO ELIMINADO")
                score += 250
                disparar = libreria.validar_comando(input("IMPRIMA COMANDO"))
                if disparar == "FUEGO":
                    print("#################################################")
                    print("#                                               #")
                    print("#                                               #")
                    print("#                                               #")
                    print("#    o                         O                #")
                    print("#   ||--------------------O ---||               #")
                    print("#   ||                         ||               #")
                    print("#                                               #")
                    print("#################################################")
                    fuego = random.randint(0, 1)
                    if fuego == comando:
                        print("#################################################")
                        print("#                                               #")
                        print("#                                               #")
                        print("#                                               #")
                        print("#    o                           O                #")
                        print("#   ||--------------------O ---||               #")
                        print("#   ||                         ||               #")
                        print("#                                               #")
                        print("#################################################")
                        print("OBJETIVO ELIMINADO")
                        score += 250
                        print("juego terminado")
                        rpta = input("DESEA GUARDAR SU SCORE? SI(1) O NO(0): ")
                        nombre = libreria.validar_contacto(input("Inrese su nombre"))
                        if rpta == "1":
                            arcivo = open("score.txt", "a")
                            arcivo.write("\n" + "nombre: " + nombre + "\n" + "Su score final es: " + str(score))
                            print("se ha guardado correctamente")
                            arcivo.close()
                        else:
                            print("ok no se guardara el score")
                    else:
                        print("##################################################")
                        print("#                                                #")
                        print("#                                                #")
                        print("#                                                #")
                        print("#                                                #")
                        print("#   o                                            #")
                        print("#  ||----                                        #")
                        print("#  ||                                            #")
                        print("##################################################")
                        print("El objetivo a escapado ")
                        score += 0
                        print("juego terminado")
                        rpta = input("DESEA GUARDAR SU SCORE? SI(1) O NO(0): ")
                        nombre = libreria.validar_contacto(input("Inrese su nombre"))
                        if rpta == "1":
                            arcivo = open("score.txt", "a")
                            arcivo.write("\n" + "nombre: " + nombre + "\n" + "Su score final es: " + str(score))
                            print("se ha guardado correctamente")
                            arcivo.close()
                        else:
                            print("no se uardara ninun dato")
                else:
                    fuego = random.randint(0, 1)
                    if fuego == comando:
                        print("#################################################")
                        print("#                                               #")
                        print("#                                               #")
                        print("#                                               #")
                        print("#    o                           O                #")
                        print("#   ||--------------------O ---||               #")
                        print("#   ||                         ||               #")
                        print("#                                               #")
                        print("#################################################")
                        print("OBJETIVO ELIMINADO")
                        score += 250
                        print("juego terminado")
                        rpta = input("DESEA GUARDAR SU SCORE? SI(1) O NO(0): ")
                        nombre = libreria.validar_contacto(input("Inrese su nombre"))
                        if rpta == "1":
                            arcivo = open("score.txt", "a")
                            arcivo.write("\n" + "nombre: " + nombre + "\n" + "Su score final es: " + str(score))
                            print("se ha guardado correctamente")
                            arcivo.close()
                        else:
                            print("ok no se guardara el score")
                    else:
                        print("##################################################")
                        print("#                                                #")
                        print("#                                                #")
                        print("#                                                #")
                        print("#                                                #")
                        print("#   o                                            #")
                        print("#  ||----                                        #")
                        print("#  ||                                            #")
                        print("##################################################")
                        print("El objetivo a escapado ")
                        score += 0
                        print("juego terminado")
                        rpta = input("DESEA GUARDAR SU SCORE? SI(1) O NO(0): ")
                        nombre = libreria.validar_contacto(input("Inrese su nombre"))
                        if rpta == "1":
                            arcivo = open("score.txt", "a")
                            arcivo.write("\n" + "nombre: " + nombre + "\n" + "Su score final es: " + str(score))
                            print("se ha guardado correctamente")
                            arcivo.close()
                        else:
                            print("ok no se guardara ningun dato")
            else:
                disparar = libreria.validar_comando(input("IMPRIMA COMANDO"))
                if disparar == "FUEGO":
                    print("#################################################")
                    print("#                                               #")
                    print("#                                               #")
                    print("#                                               #")
                    print("#    o                         O                #")
                    print("#   ||--------------------O ---||               #")
                    print("#   ||                         ||               #")
                    print("#                                               #")
                    print("#################################################")
                    fuego = random.randint(0, 1)
                    if fuego == comando:
                        print("#################################################")
                        print("#                                               #")
                        print("#                                               #")
                        print("#                                               #")
                        print("#    o                           O                #")
                        print("#   ||--------------------O ---||               #")
                        print("#   ||                         ||               #")
                        print("#                                               #")
                        print("#################################################")
                        print("OBJETIVO ELIMINADO")
                        score += 250
                        print("juego terminado")
                        rpta = input("DESEA GUARDAR SU SCORE? SI(1) O NO(0): ")
                        nombre = libreria.validar_contacto(input("Inrese su nombre"))
                        if rpta == "1":
                            arcivo = open("score.txt", "a")
                            arcivo.write("\n" + "nombre: " + nombre + "\n" + "Su score final es: " + str(score))
                            print("se ha guardado correctamente")
                            arcivo.close()
                        else:
                            print("ok no se guardara el score")
                    else:
                        print("##################################################")
                        print("#                                                #")
                        print("#                                                #")
                        print("#                                                #")
                        print("#                                                #")
                        print("#   o                                            #")
                        print("#  ||----                                        #")
                        print("#  ||                                            #")
                        print("##################################################")
                        print("El objetivo a escapado ")
                        score += 0
                        print("juego terminado")
                        rpta = input("DESEA GUARDAR SU SCORE? SI(1) O NO(0): ")
                        nombre = libreria.validar_contacto(input("Inrese su nombre"))
                        if rpta == "1":
                            arcivo = open("score.txt", "a")
                            arcivo.write("\n" + "nombre: " + nombre + "\n" + "Su score final es: " + str(score))
                            print("se ha guardado correctamente")
                            arcivo.close()
                        else:
                            print("no se guardara ningun dato")


def ver_score():
    arcivo=open("score.txt","r+")
    print(arcivo)
    arcivo.close()

import libreria
opc=0
max=3
while opc!=max:
    print("#############CONTRA DEMO#############")
    print("#1.INICIAR JUEGO                    #")
    print("#2.VER SCORES MAXIMOS DE JUADORES   #")
    print("#3.SALIR                            #")
    print("#####################################")
    opc=libreria.validar_menu(input("Inrese su opcion"))
    if opc==1:
        iniciar_juego()
    if opc==2:
        ver_score()
